### ISSUE TITLE
Proper way to update Unbound?

### ISSUE THREAD

**Issue by mattredact** [ar51an/unbound-redis#11]
What's the best practice for updating unbound? Re-compiling with the same flags? Everything else should work in place, correct?

Thanks for the lovely project. :)

**Comment by ar51an** [comment]
Yes that is exactly how I do. It is mentioned in the release.md under Upgrade:

https://github.com/ar51an/unbound-redis/blob/main/release.md#upgrade

**Comment by mattredact** [comment]
Awesome. Seemed to miss that. Thank you!

**Comment by ar51an** [comment]
You are welcome. I am currently on Unbound 1.19.3. If there is any change in the build process (or) any major change in Unbound functionality, at that time I update the documentation in this repo with the new release (if needed).
