### ISSUE TITLE
Stupid question about "add unbound user to redis group"

### ISSUE THREAD

**Issue by BliXem1** [ar51an/unbound-redis#14]
Can you tell me how? :)

**Comment by ar51an** [comment]
Add unbound user to redis group:
`sudo adduser unbound redis`

As a reference it is required if you set the socket permission to `unixsocketperm 770` in `redis.conf`

If in future you want to remove unbound user form redis group:
`sudo deluser unbound redis`

**Comment by BliXem1** [comment]
Thanks! Still get a permission denied if I restart unbound, weird huh? Also after sudo adduser unbound redis and the perm on 770 within redis.conf.

**Comment by ar51an** [comment]
I just tested it right now and it is working fine.

![image](https://github.com/user-attachments/assets/1d7c823c-7fed-43b2-b6ce-795aa614d0ec)

![image](https://github.com/user-attachments/assets/2fcc289e-f573-4ff0-9b5b-20e263f37374)

What is the output of below cmd after adding unbound user to redis group?
`id unbound`

**Comment by BliXem1** [comment]
Hi,


```
root@dnsserver:~# id unbound
uid=110(unbound) gid=110(unbound) groups=110(unbound),111(redis)
root@dnsserver:~# sudo redis-cli -s /var/run/redis/redis.sock config get unixsocketperm
1) "unixsocketperm"
2) "770"
root@dnsserver:~# sudo redis-cli -s /var/run/redis/redis.sock config get unixsocket
1) "unixsocket"
2) "/var/run/redis/redis.sock"
```

It's weird, it won't start here. But I must be honest, it's not on a Pi but on Ubuntu :).

**Comment by ar51an** [comment]
Can you paste the error?

**Comment by BliXem1** [comment]
```
Aug 20 10:19:27 dnsserver systemd[1]: Starting unbound.service - Unbound DNS server...
░░ Subject: A start job for unit unbound.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit unbound.service has begun execution.
░░
░░ The job identifier is 4028.
Aug 20 10:19:27 dnsserver (unbound)[1504]: unbound.service: Referenced but unset environment variable evaluates to an empty string: DAEMON_OPTS
Aug 20 10:19:27 dnsserver unbound[1504]: [1504:0] error: failed to connect to redis server: Permission denied
Aug 20 10:19:27 dnsserver unbound[1504]: [1504:0] error: redis_init: failed to init redis
Aug 20 10:19:27 dnsserver unbound[1504]: [1504:0] error: cachedb: could not init redis backend
Aug 20 10:19:27 dnsserver unbound[1504]: [1504:0] error: module init for module cachedb failed
Aug 20 10:19:27 dnsserver unbound[1504]: [1504:0] fatal error: failed to setup modules
Aug 20 10:19:27 dnsserver systemd[1]: unbound.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit unbound.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 20 10:19:27 dnsserver systemd[1]: unbound.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit unbound.service has entered the 'failed' state with result 'exit-code'.
Aug 20 10:19:27 dnsserver systemd[1]: Failed to start unbound.service - Unbound DNS server.

```

**Comment by ar51an** [comment]
I think in Ubuntu the user need to logout and log back in after adding to a new group. Try to restart the system.

**Comment by BliXem1** [comment]
I tried a reboot but that doesn't fix it either. If you out of idea's I will let it on 127.0.0.1, then all works perfectly.

**Comment by ar51an** [comment]
Does it work with unixsocketperm 707?

**Comment by BliXem1** [comment]
No, still the same failure then.

**Comment by ar51an** [comment]
With unixsocketperm 707 you do not need to add unbound user to redis group.
There is some other issue going on. Are you sure the redis is creating the socket and there is no error in redis log?

**Comment by BliXem1** [comment]
Error log is empty, but I will check. Thanks for the support! :)

**Comment by ar51an** [comment]
You are welcome. It should be with these permissions when you use `unixsocketperm 707`:
![image](https://github.com/user-attachments/assets/a5d98a84-91b5-4d64-91f7-95955623deba)
