### ISSUE TITLE
script post install and config

### ISSUE THREAD

**Issue by niammuddin** [ar51an/unbound-redis#4]
hi!

can you share  all config file .conf
post-install.sh
install-timers.sh
update-roothints.sh
update-blocklists.sh
post-remove.sh

**Comment by ar51an** [comment]
Hello,
Did you try to download the release? The readme clearly indicates where ever a config file is referenced it is "in the release" along with exact dir location in it.

https://github.com/ar51an/unbound-redis/releases/download/v1.1/unbound-redis-release-1.1.tar.gz

![image](https://github.com/ar51an/unbound-redis/assets/11185794/8c003e8f-5a66-4ed7-818b-ff839f5926ca)

**Comment by niammuddin** [comment]
Hi, Thank now i see, 
because before i see from here
![image](https://github.com/ar51an/unbound-redis/assets/6014789/702a3bae-c4d6-4b10-a1b1-83377823be0c)

**Comment by ar51an** [comment]
It is there in the image you posted above. You can download the release by clicking either 1 or 2. I marked them in the above image:


![image](https://github.com/ar51an/unbound-redis/assets/11185794/8220b896-0183-4b18-872a-098669e9d1f2)
