### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by by-carlos** [ar51an/unbound-redis#7]
Hi @ar51an 

First of all, I wanted to drop a line and say I loved your setup. Is so impressive. I was only looking for someone who had set up Redis with Unbound, but this looks so much better than anything I came across so far. And the dashboard. And it would remove hops and components from my setup.

I'm running everything on Docker (my NAS works as a server for pretty much everything). I guess you're not considering supporting Docker as you're running everything on a RaspberryPi. Considering on copying what you did, any pointers on how to start setting this up on Docker? :)

Cheers

**Comment by mtpham99** [comment]
> 

> Hi @ar51an
> 
> First of all, I wanted to drop a line and say I loved your setup. Is so impressive. I was only looking for someone who had set up Redis with Unbound, but this looks so much better than anything I came across so far. And the dashboard. And it would remove hops and components from my setup.
> 
> I'm running everything on Docker (my NAS works as a server for pretty much everything). I guess you're not considering supporting Docker as you're running everything on a RaspberryPi. Considering on copying what you did, any pointers on how to start setting this up on Docker? :)
> 
> Cheers

Sorry for replying to old issues, but I wanted to mention that I have an unbound-redis setup using docker and thought I'd share it. Link to it [here](https://github.com/mtpham99/unbound-redis-metrics).

**Comment by by-carlos** [comment]
Thanks @mtpham99. I completed the setup a while ago, my bad as I didn't update the thread. I can upload the configuration file... It's been running for so long that I forgot about it. Is the downside about things that work properly: I don't remember how I did it anymore. :)

Cheers

**Comment by aqtoo** [comment]
Is it worth attempting to at least use the redis config + unbound config when inside a docker container? (Of course altered as needed for inside a container)
