### ISSUE TITLE
Unbound startup problems - missing /var/lib/unbound/root.key

### ISSUE THREAD

**Issue by Malzmeier** [ar51an/unbound-redis#9]
Hi,

I followed your guide to setup unbound + Redis.

After trying to start unbound is missing the /var/lib/unbound/root.key
`Apr 24 11:46:06 dns unbound[14365]: [14365:0] error: unable to open /var/lib/unbound/root.key for reading: No such file or directory
Apr 24 11:46:06 dns unbound[14365]: [14365:0] error: error reading auto-trust-anchor-file: /var/lib/unbound/root.key
Apr 24 11:46:06 dns unbound[14365]: [14365:0] error: validator: error in trustanchors config
Apr 24 11:46:06 dns unbound[14365]: [14365:0] error: validator: could not apply configuration settings.
Apr 24 11:46:06 dns unbound[14365]: [14365:0] error: module init for module validator failed
Apr 24 11:46:06 dns unbound[14365]: [14365:0] fatal error: failed to setup modules`

I tried to use unbound-anchor but it also fails.
`unbound-anchor: error while loading shared libraries: libunbound.so.8: cannot open shared object file: No such file or directory`

The only difference to your guide is that I'm on an x86 machine and removed the `--build=aarch64-linux-gnu` flag on configure.

Any suggestions?

**Comment by Malzmeier** [comment]
My fault.
Forgot to remove `--libdir=\${prefix}/lib/aarch64-linux-gnu` on configure.

Now after `unbound-anchor -a /var/lib/unbound/root.key` it works :-)

**Comment by rj-d2** [comment]
@Malzmeier thank you for pointing this out, was trying to install in on x64 architecture, and had the same problem.

for future reference, this is working for x86_64

```
./configure --build=x86_64-linux-gnu \
--prefix=/usr \
--includedir=${prefix}/include \
--infodir=${prefix}/share/info \
--libdir=${prefix}/lib/x86_64-linux-gnu \
--mandir=${prefix}/share/man \
--localstatedir=/var \
--runstatedir=/run \
--sysconfdir=/etc \
--with-chroot-dir= \
--with-dnstap-socket-path=/run/dnstap.sock \
--with-libevent \
--with-libhiredis \
--with-libnghttp2 \
--with-pidfile=/run/unbound.pid \
--with-pythonmodule \
--with-pyunbound \
--with-rootkey-file=/var/lib/unbound/root.key \
--disable-dependency-tracking \
--disable-flto \
--disable-maintainer-mode \
--disable-option-checking \
--disable-rpath \
--disable-silent-rules \
--enable-cachedb \
--enable-dnstap \
--enable-subnet \
--enable-systemd \
--enable-tfo-client \
--enable-tfo-server
```
